blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://linksgo.vercel.app/docs
    about: Check our documentation for guides and troubleshooting
  - name: 💬 Community Support
    url: https://github.com/LinksGo/linksgo/discussions
    about: Please ask and answer questions here
  - name: 🔒 Security Issues
    url: https://github.com/LinksGo/linksgo/security/policy
    about: Please report security vulnerabilities here
