export const themes = {
  default: {
    name: 'Default',
    background: 'bg-gradient-to-br from-blue-500 to-blue-600',
    text: 'text-white',
    subtext: 'text-blue-100',
    buttonVariant: 'shadow',
    buttonColor: 'primary',
    socialIconColor: 'text-white hover:text-blue-200',
    avatarColor: 'primary',
    sideColor: 'bg-gradient-to-br from-blue-600 to-blue-700',
    linkButton: 'bg-white/20 backdrop-blur-sm border-white/20 hover:bg-white/30 text-white'
  },
  neonPunk: {
    name: 'Neon Punk',
    background: 'bg-gradient-to-br from-fuchsia-600 via-purple-600 to-pink-600',
    text: 'text-white',
    subtext: 'text-fuchsia-200',
    buttonVariant: 'shadow',
    buttonColor: 'secondary',
    socialIconColor: 'text-white hover:text-fuchsia-200',
    avatarColor: 'secondary',
    sideColor: 'bg-gradient-to-br from-fuchsia-700 to-purple-700',
    linkButton: 'bg-white/20 backdrop-blur-sm border-fuchsia-500/30 hover:bg-white/30 text-white'
  },
  sunset: {
    name: 'Sunset Vibes',
    background: 'bg-gradient-to-br from-orange-500 via-red-500 to-purple-600',
    text: 'text-white',
    subtext: 'text-orange-100',
    buttonVariant: 'shadow',
    buttonColor: 'warning',
    socialIconColor: 'text-white hover:text-orange-200',
    avatarColor: 'warning',
    sideColor: 'bg-gradient-to-br from-orange-600 to-red-600',
    linkButton: 'bg-white/20 backdrop-blur-sm border-orange-500/30 hover:bg-white/30 text-white'
  },
  emerald: {
    name: 'Emerald Forest',
    background: 'bg-gradient-to-br from-emerald-400 to-green-600',
    text: 'text-white',
    subtext: 'text-emerald-100',
    buttonVariant: 'shadow',
    buttonColor: 'success',
    socialIconColor: 'text-white hover:text-emerald-200',
    avatarColor: 'success',
    sideColor: 'bg-gradient-to-br from-emerald-600 to-green-700',
    linkButton: 'bg-white/20 backdrop-blur-sm border-emerald-500/30 hover:bg-white/30 text-white'
  },
  midnight: {
    name: 'Midnight Galaxy',
    background: 'bg-gradient-to-br from-indigo-600 via-purple-600 to-blue-600',
    text: 'text-white',
    subtext: 'text-indigo-200',
    buttonVariant: 'shadow',
    buttonColor: 'secondary',
    socialIconColor: 'text-white hover:text-indigo-200',
    avatarColor: 'secondary',
    sideColor: 'bg-gradient-to-br from-indigo-700 to-purple-700',
    linkButton: 'bg-white/20 backdrop-blur-sm border-indigo-500/30 hover:bg-white/30 text-white'
  },
  coral: {
    name: 'Coral Reef',
    background: 'bg-gradient-to-br from-cyan-400 via-teal-500 to-blue-500',
    text: 'text-white',
    subtext: 'text-cyan-100',
    buttonVariant: 'shadow',
    buttonColor: 'primary',
    socialIconColor: 'text-white hover:text-cyan-200',
    avatarColor: 'primary',
    sideColor: 'bg-gradient-to-br from-cyan-600 to-teal-600',
    linkButton: 'bg-white/20 backdrop-blur-sm border-cyan-500/30 hover:bg-white/30 text-white'
  },
  autumn: {
    name: 'Autumn Breeze',
    background: 'bg-gradient-to-br from-amber-500 via-orange-500 to-red-500',
    text: 'text-white',
    subtext: 'text-amber-100',
    buttonVariant: 'shadow',
    buttonColor: 'warning',
    socialIconColor: 'text-white hover:text-amber-200',
    avatarColor: 'warning',
    sideColor: 'bg-gradient-to-br from-amber-600 to-orange-600',
    linkButton: 'bg-white/20 backdrop-blur-sm border-amber-500/30 hover:bg-white/30 text-white'
  },
  aurora: {
    name: 'Northern Lights',
    background: 'bg-gradient-to-br from-green-400 via-teal-500 to-blue-500',
    text: 'text-white',
    subtext: 'text-green-100',
    buttonVariant: 'shadow',
    buttonColor: 'success',
    socialIconColor: 'text-white hover:text-green-200',
    avatarColor: 'success',
    sideColor: 'bg-gradient-to-br from-green-600 to-teal-600',
    linkButton: 'bg-white/20 backdrop-blur-sm border-green-500/30 hover:bg-white/30 text-white'
  },
  rose: {
    name: 'Rose Gold',
    background: 'bg-gradient-to-br from-rose-400 via-pink-500 to-orange-400',
    text: 'text-white',
    subtext: 'text-rose-100',
    buttonVariant: 'shadow',
    buttonColor: 'danger',
    socialIconColor: 'text-white hover:text-rose-200',
    avatarColor: 'danger',
    sideColor: 'bg-gradient-to-br from-rose-500 to-pink-600',
    linkButton: 'bg-white/20 backdrop-blur-sm border-rose-500/30 hover:bg-white/30 text-white'
  },
  ocean: {
    name: 'Deep Ocean',
    background: 'bg-gradient-to-br from-blue-600 via-blue-700 to-indigo-800',
    text: 'text-white',
    subtext: 'text-blue-100',
    buttonVariant: 'shadow',
    buttonColor: 'primary',
    socialIconColor: 'text-white hover:text-blue-200',
    avatarColor: 'primary',
    sideColor: 'bg-gradient-to-br from-blue-700 to-indigo-800',
    linkButton: 'bg-white/20 backdrop-blur-sm border-blue-500/30 hover:bg-white/30 text-white'
  },
  dark: {
    name: 'Dark Mode',
    background: 'bg-gradient-to-br from-gray-800 to-gray-900',
    text: 'text-white',
    subtext: 'text-gray-300',
    buttonVariant: 'shadow',
    buttonColor: 'default',
    socialIconColor: 'text-gray-400 hover:text-white',
    avatarColor: 'default',
    sideColor: 'bg-gradient-to-br from-gray-900 to-black',
    linkButton: 'bg-white/10 backdrop-blur-sm border-gray-700 hover:bg-white/20 text-white'
  }
}
